version: "3.8"
services:
  whoami:
    container_name: "whoami"
    image: jwilder/whoami
    networks:
      - caddy
    labels:
      caddy: whoami.videah.net
      caddy.reverse_proxy: "{{upstreams 8000}}"

networks:
  caddy:
    external: true
