version: "3.8"
services:
  dall_e_gallery:
    container_name: "dall-e-gallery"
    image: videah/dall-e-gallery:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - caddy
    labels:
      caddy: dall-e.videah.net
      caddy.reverse_proxy: "{{upstreams 80}}"
      com.centurylinklabs.watchtower.enable: true

networks:
  caddy:
    external: true
