version: "3.8"
services:
  caddy:
    container_name: "caddy"
    image: videah/caddy-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    labels:
      caddy.email: "videah@selfish.systems"
      com.centurylinklabs.watchtower.enable: true

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
