version: "3.8"
services:
  watchtower:
    container_name: "watchtower"
    image: containrrr/watchtower:latest
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    labels:
      com.centurylinklabs.watchtower.enable: true
    command: --interval 120