version: "3.8"
services:
  videah_net:
    container_name: "videah_net_new"
    image: videah/videah-net:latest
    networks:
      - caddy
    labels:
      caddy: videah.net
      caddy.reverse_proxy: "{{upstreams 80}}"
      # Redirect to my fursona's references, useful for commissioning art
      caddy.0_redir: "/references ${VIDEAH_REFERENCES_URL}"
      # We do both ways here because I can legit never remember which order it is
      caddy.1_redir: "/dad-references ${VIDEAH_DAD_REFERENCES_URL}"
      caddy.2_redir: "/references-dad ${VIDEAH_DAD_REFERENCES_URL}"

networks:
  caddy:
    external: true
